// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Func5Reader is a Reader for the Func5 structure.
type Func5Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Func5Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunc5OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFunc5OK creates a Func5OK with default headers values
func NewFunc5OK() *Func5OK {
	return &Func5OK{}
}

/*Func5OK handles this case with default header values.

OK
*/
type Func5OK struct {
}

func (o *Func5OK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/debug/pprof/trace][%d] func5OK ", 200)
}

func (o *Func5OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
