// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Func3Reader is a Reader for the Func3 structure.
type Func3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Func3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunc3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFunc3OK creates a Func3OK with default headers values
func NewFunc3OK() *Func3OK {
	return &Func3OK{}
}

/*Func3OK handles this case with default header values.

OK
*/
type Func3OK struct {
}

func (o *Func3OK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/debug/pprof/profile][%d] func3OK ", 200)
}

func (o *Func3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
