// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Func4Reader is a Reader for the Func4 structure.
type Func4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Func4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunc4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFunc4OK creates a Func4OK with default headers values
func NewFunc4OK() *Func4OK {
	return &Func4OK{}
}

/*Func4OK handles this case with default header values.

OK
*/
type Func4OK struct {
}

func (o *Func4OK) Error() string {
	return fmt.Sprintf("[GET /api/v1alpha1/debug/pprof/symbols][%d] func4OK ", 200)
}

func (o *Func4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
