// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFunc4Params creates a new Func4Params object
// with the default values initialized.
func NewFunc4Params() *Func4Params {

	return &Func4Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewFunc4ParamsWithTimeout creates a new Func4Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewFunc4ParamsWithTimeout(timeout time.Duration) *Func4Params {

	return &Func4Params{

		timeout: timeout,
	}
}

// NewFunc4ParamsWithContext creates a new Func4Params object
// with the default values initialized, and the ability to set a context for a request
func NewFunc4ParamsWithContext(ctx context.Context) *Func4Params {

	return &Func4Params{

		Context: ctx,
	}
}

// NewFunc4ParamsWithHTTPClient creates a new Func4Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFunc4ParamsWithHTTPClient(client *http.Client) *Func4Params {

	return &Func4Params{
		HTTPClient: client,
	}
}

/*Func4Params contains all the parameters to send to the API endpoint
for the func4 operation typically these are written to a http.Request
*/
type Func4Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the func4 params
func (o *Func4Params) WithTimeout(timeout time.Duration) *Func4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the func4 params
func (o *Func4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the func4 params
func (o *Func4Params) WithContext(ctx context.Context) *Func4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the func4 params
func (o *Func4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the func4 params
func (o *Func4Params) WithHTTPClient(client *http.Client) *Func4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the func4 params
func (o *Func4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *Func4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
