// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Func2Reader is a Reader for the Func2 structure.
type Func2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Func2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunc2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFunc2OK creates a Func2OK with default headers values
func NewFunc2OK() *Func2OK {
	return &Func2OK{}
}

/*Func2OK handles this case with default header values.

OK
*/
type Func2OK struct {
}

func (o *Func2OK) Error() string {
	return fmt.Sprintf("[GET /debug/pprof/cmdline][%d] func2OK ", 200)
}

func (o *Func2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
