// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFunc5Params creates a new Func5Params object
// with the default values initialized.
func NewFunc5Params() *Func5Params {

	return &Func5Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewFunc5ParamsWithTimeout creates a new Func5Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewFunc5ParamsWithTimeout(timeout time.Duration) *Func5Params {

	return &Func5Params{

		timeout: timeout,
	}
}

// NewFunc5ParamsWithContext creates a new Func5Params object
// with the default values initialized, and the ability to set a context for a request
func NewFunc5ParamsWithContext(ctx context.Context) *Func5Params {

	return &Func5Params{

		Context: ctx,
	}
}

// NewFunc5ParamsWithHTTPClient creates a new Func5Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFunc5ParamsWithHTTPClient(client *http.Client) *Func5Params {

	return &Func5Params{
		HTTPClient: client,
	}
}

/*Func5Params contains all the parameters to send to the API endpoint
for the func5 operation typically these are written to a http.Request
*/
type Func5Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the func5 params
func (o *Func5Params) WithTimeout(timeout time.Duration) *Func5Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the func5 params
func (o *Func5Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the func5 params
func (o *Func5Params) WithContext(ctx context.Context) *Func5Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the func5 params
func (o *Func5Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the func5 params
func (o *Func5Params) WithHTTPClient(client *http.Client) *Func5Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the func5 params
func (o *Func5Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *Func5Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
