// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Func1Reader is a Reader for the Func1 structure.
type Func1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Func1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunc1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFunc1OK creates a Func1OK with default headers values
func NewFunc1OK() *Func1OK {
	return &Func1OK{}
}

/*Func1OK handles this case with default header values.

OK
*/
type Func1OK struct {
}

func (o *Func1OK) Error() string {
	return fmt.Sprintf("[GET /debug/pprof][%d] func1OK ", 200)
}

func (o *Func1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
