apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: helm-operator
  namespace: flux
spec:
  componentKinds:
    - group: apps
      kind: Deployment
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-helm-operator
